"""empty message

Revision ID: d1d19fdf438c
Revises: dee938c160fc
Create Date: 2025-01-28 09:39:12.329396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d19fdf438c'
down_revision = 'dee938c160fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('diameter',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('population',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('orbital_period',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('rotation_period',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('rotation_period',
               existing_type=sa.String(length=80),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
        batch_op.alter_column('orbital_period',
               existing_type=sa.String(length=80),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
        batch_op.alter_column('population',
               existing_type=sa.String(length=80),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
        batch_op.alter_column('diameter',
               existing_type=sa.String(length=80),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    # ### end Alembic commands ###
